// <auto-generated />
namespace GCloud.Models.Domain
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddingNewColumnsInCompanies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNewColumnsInCompanies));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050512083_AddingNewColumnsInCompanies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
